### ISSUE TITLE
Request not working

### ISSUE THREAD

**Issue by jelecool** [sdushantha/instadp#3]
Hi,

I am trying to use the script but the call to get the file URL returns a 200 without any data.

So it breaks at r.json()

Any idea why ? Has the url for the api changed? 

Thanks

**Comment by sdushantha** [comment]
Thank you for letting me know about this problem. You correct, the API has changed. It now redirects to a login page. 

I might have to try to find another way to get the profile pictures.

**Comment by jelecool** [comment]
Can I be of any help?

Thanks :)

[image: leo.solutions]
Jean-Emrick Rioux
Ventes et Marketing

[image: leo.solutions] <4503757599> 450 375-7599 <4503757599>


[image: leo.solutions] <514269-3272> 514-269-3272 <514269-3272>


*www.leo.solutions* <https://leo.solutions/>


[image: leo.solutions] <https://www.facebook.com/leosolutionsweb/> [image:
leo.solutions] <https://www.linkedin.com/company/leo-solutions>
[image: leo.solutions]
<https://www.instagram.com/leo.solutions/?hl=fr-ca> [image:
leo.solutions] <https://goo.gl/maps/1V8uUTeF4RF2>
<https://www.google.com/partners/agency?hl=fr>

On January 11, 2019 at 1:36:02 PM, Siddharth Dushantha (
notifications@github.com) wrote:

Thank you for letting me know about this problem. You correct, the API has
changed. It now redirects to a login page.

I might have to try to find another way to get the profile pictures.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/sdushantha/instadp/issues/3#issuecomment-453614354>,
or mute
the thread

**Comment by sdushantha** [comment]
You are more than welcome to help! 😊
If you find a method to get the profile picture in good quality just let me know.

**Comment by sdushantha** [comment]
@jelecool 
Hey, it works now perfectly fine now :)
