### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by rootftw** [sdushantha/instadp#4]
Following your directions to install and i'm receiving this error:

Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-J6yKvb/instadp/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-GMh2wM-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-J6yKvb/instadp/

**Comment by sdushantha** [comment]
Not really sure why that is happening. I will try to fix this.

**Comment by sdushantha** [comment]
@rootftw this as been fixed now :)
You can install it pip now :D
